###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################
# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: https-self
      port: {{ .Values.proxy.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: "{{ .Values.name }}"
    release: {{ .Release.Name }}



