# Copyright (c) 2020 Red Hat, Inc.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kui-metrics-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]