# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kui-web-terminal-metrics
  # the service monitor has to be in the OCP Prometheus namespace
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: https-self
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector: {}