#
# Copyright (c) 2020 Red Hat, Inc.
#

###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.name }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        k8s-app: "{{ .Values.proxy.name }}"
        component: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
      serviceAccountName: {{ .Values.proxy.name }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  {{- if .Values.arch }}
                  - {{ .Values.arch }}
                  {{- else }}
                  - {{ template "kui-proxy.arch" . }}
                  {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.name }}
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.name }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Values.proxy.name }}
        image: {{ .Values.global.imageOverrides.kui_web_terminal }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: "/status/livenessProbe"
            port: 3000
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: "/status/readinessProbe"
            port: 3000
            scheme: HTTPS
        env:
        - name: ICP_EXTERNAL_URL
          value: "https://{{ .Values.proxy.clusterIP }}:{{ .Values.proxy.clusterPort }}"
        - name: KUI_INGRESS_PATH
          value: "{{ .Values.proxy.ingressPath }}"
        - name: USE_CLOUDPAK_SETTINGS
          value: {{if .Values.proxy.env.useOpenshiftSettings }}"false"{{else}}"true"{{end}}
        - name: TOKEN_FROM_COOKIE
          value: {{if .Values.proxy.env.tokenFromCookie }}"true"{{else}}"false"{{end}}
        - name: ACCESS_TOKEN_KEY
          value: {{ .Values.proxy.env.accessTokenKey }}
        - name: HEADER_SERVICE
          value: {{ .Values.proxy.env.headerURL }}

        volumeMounts:
        - name: "{{ .Values.volumeMounts.kuiCertsName }}"
          mountPath: "{{ .Values.volumeMounts.kuiCertsMountPath }}"
        resources:
{{ toYaml .Values.proxy.resources | indent 10 }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}
      volumes:
      - name: "{{ .Values.volumes.kuiCertsName }}"
        secret:
          secretName: "{{ .Values.volumes.kuiCertsSecretName }}"
