###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ .Values.proxy.name }}
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    ingress.open-cluster-management.io/auth-type: "access-token"
    ingress.open-cluster-management.io/secure-backends: "true"
    ingress.open-cluster-management.io/configuration-snippet: |
      add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Content-Security-Policy "frame-ancestors 'none'";
            add_header Pragma no-cache;
            add_header Expires 0;
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Values.proxy.ingressPath }}"
        backend:
          serviceName: {{ .Values.proxy.name }}
          servicePort: {{ .Values.proxy.service.port }}