# Copyright (c) 2020 Red Hat, Inc.
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kui-proxy
  labels:
    component: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kui-proxy
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: kui-proxy
  apiGroup: rbac.authorization.k8s.io
