###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ .Values.proxy.name }}"
  labels:
    app: {{ .Values.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}  
spec:
  secretName: "{{ .Values.volumes.kuiCertsSecretName }}"
  issuerRef:
    name: multicloud-ca-issuer
    kind: Issuer
  commonName: kui-proxy
  dnsNames:
  - kui-proxy.kube-system
  - kui-proxy.kube-system.svc
  - localhost
  - 127.0.0.1