###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

name: kui-web-terminal
replicaCount: 1

pullSecret: null
arch: ""

proxy:
  env:
    useOpenshiftSettings: true
    tokenFromCookie: true
    accessTokenKey: acm-access-token-cookie
    headerURL: http://console-header:3000
  clusterIP: icp-management-ingress
  clusterPort: 8443
  name: kui-proxy
  ingressPath: kui
  service:
    port: 8081
  image:
    repository: quay.io/repository/open-cluster-management
    name: kui-web-terminal
    tag: 3.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi

imageTagPostfix: ""

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"

volumes:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsSecretName: "kui-proxy-secret"

volumeMounts:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsMountPath: "/etc/certs"
