#
# Copyright (c) 2020 Red Hat, Inc.
#

###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

name: kui-web-terminal
replicaCount: 1

pullSecret: null
arch: ""

global:
  pullPolicy: Always
  imageOverrides:
    kui_web_terminal: ""

proxy:
  env:
    useOpenshiftSettings: true
    tokenFromCookie: true
    accessTokenKey: acm-access-token-cookie
    headerURL: http://console-header:3000
  clusterIP: icp-management-ingress
  clusterPort: 8443
  name: kui-proxy
  ingressPath: kui
  service:
    port: 8081
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    
hubconfig:
  nodeSelector: null

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kui-web-terminal
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kui-web-terminal

volumes:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsSecretName: "kui-proxy-secret"

volumeMounts:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsMountPath: "/etc/certs"
